import { cmdHandlers } from "../../handlers/IdChatMessage";
import { CommandHandler } from "../../types";
import { sendAsServer } from "../../util";

const games = [
	"SNES Mario Circuit 3",
	"SNES Bowser Castle 3",
	"SNES Donut Plains 3",
	"SNES Rainbow Road",
	"N64 Kalimari Desert",
	"N64 Toad's Turnpike",
	"N64 Choco Mountain",
	"N64 Royal Raceway",
	"N64 Yoshi Valley",
	"N64 Rainbow Road",
	"GBA Riverside Park",
	"GBA Mario Circuit",
	"GBA Boo Lake",
	"GBA Cheese Land",
	"GBA Sky Garden",
	"GBA Sunset Wilds",
	"GBA Snow Land",
	"GBA Ribbon Road",
	"GCN Baby Park",
	"GCN Dry Dry Desert",
	"GCN Daisy Cruiser",
	"GCN Waluigi Stadium",
	"GCN Sherbet Land",
	"GCN Yoshi Circuit",
	"GCN DK Mountain",
	"DS Cheep Cheep Beach",
	"DS Waluigi Pinball",
	"DS Shroom Ridge",
	"DS Tick-Tock Clock",
	"DS Mario Circuit",
	"DS Wario Stadium",
	"DS Peach Gardens",
	"Wii Moo Moo Meadows",
	"Wii Mushroom Gorge",
	"Wii Coconut Mall",
	"Wii DK Summit",
	"Wii Wario's Gold Mine",
	"Wii Daisy Circuit",
	"Wii Koopa Cape",
	"Wii Maple Treeway",
	"Wii Grumble Volcano",
	"Wii Moonview Highway",
	"Wii Rainbow Road",
	"3DS Toad Circuit",
	"3DS Music Park",
	"3DS Rock Rock Mountain",
	"3DS Piranha Plant Slide",
	"3DS Neo Bowser City",
	"3DS DK Jungle",
	"3DS Rosalina's Ice World",
	"3DS Rainbow Road",
	"Mario Kart Stadium",
	"Water Park",
	"Sweet Sweet Canyon",
	"Twomp Ruins",
	"Mario Circuit",
	"Toad Harbor",
	"Twisted Mansion",
	"Shy Guy Falls",
	"Sunshine Airport",
	"Dolphin Shoals",
	"Electrodrome",
	"Mount Wario",
	"Cloudtop Cruise",
	"Bone-Dry Dunes",
	"Bowser's Castle",
	"Rainbow Road",
	"Excitebike Arena",
	"Dragon Driftway",
	"Mute City",
	"Ice Ice Outpost",
	"Hyrule Circuit",
	"Wild Woods",
	"Animal Crossing",
	"Super Bell Subway",
	"Big Blue",
	"Tour New York Minute",
	"Tour Tokio Blur",
	"Tour Paris Promenade",
	"Tour London Loop",
	"Tour Vancouver Velocity",
	"Tour Los Angeles Laps",
	"Merry Mountain",
	"Tour Berlin Byways",
	"Ninja Hideaway",
	"Tour Sidney Sprint",
	"Tour Singapore Speedway",
	"Tour Amsterdam Drift",
	"Tour Bangkok Rush",
	"Sky-High Sundae",
	"Piranha Plant Cove",
	"Yoshi's Island",
	"Tour Athens Dash",
	"Tour Rome Avanti",
	"Squeaky Clean Sprint",
	"Tour Madrid Drive",
];

export const track: CommandHandler = {
	fn: (args: string[]) => {
		const index = Math.floor(Math.random() * games.length);
		const game = games[index];
		sendAsServer(`Your random track is: ${game}`);
	},
	signature: "/track",
};
